name: seoul
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.12=h4c7d964_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.17=py311h5dfdfe8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h9214b88_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.7.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - krb5=1.21.3=hdf4eb48_0
  - libffi=3.4.4=hd77b12b_1
  - libsodium=1.0.20=hc70643c_0
  - libzlib=1.3.1=h02ab6af_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.0=h725018a_0
  - parso=0.8.5=pyhcf101f3_0
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py311hf893f09_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.11.14=h981015d_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=2_cp311
  - pywin32=311=py311hefeebc8_1
  - pyzmq=27.1.0=py311hb77b9c8_0
  - setuptools=80.9.0=py311haa95532_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=hf199647_0
  - tornado=6.5.2=py311h3485c13_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anthropic==0.73.0
      - anyio==4.11.0
      - asgiref==3.10.0
      - attrs==25.4.0
      - backoff==2.2.1
      - bcrypt==5.0.0
      - build==1.3.0
      - cachetools==6.2.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - chroma-hnswlib==0.7.6
      - chromadb==0.5.20
      - click==8.3.1
      - coloredlogs==15.0.1
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - docstring-parser==0.17.0
      - durationpy==0.10
      - fastapi==0.115.0
      - filelock==3.20.0
      - flatbuffers==25.9.23
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - google-auth==2.43.0
      - google-genai==1.50.1
      - googleapis-common-protos==1.72.0
      - greenlet==3.2.4
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - huggingface-hub==1.1.4
      - humanfriendly==10.0
      - idna==3.11
      - importlib-resources==6.5.2
      - jiter==0.12.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - kubernetes==34.1.0
      - langchain==0.3.7
      - langchain-community==0.3.7
      - langchain-core==0.3.63
      - langchain-openai==0.2.9
      - langchain-text-splitters==0.3.8
      - langsmith==0.1.147
      - markdown-it-py==4.0.0
      - marshmallow==3.26.1
      - mdurl==0.1.2
      - mmh3==5.2.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - numpy==1.26.4
      - oauthlib==3.3.1
      - onnxruntime==1.23.2
      - openai==2.8.0
      - opentelemetry-api==1.38.0
      - opentelemetry-exporter-otlp-proto-common==1.38.0
      - opentelemetry-exporter-otlp-proto-grpc==1.38.0
      - opentelemetry-instrumentation==0.59b0
      - opentelemetry-instrumentation-asgi==0.59b0
      - opentelemetry-instrumentation-fastapi==0.59b0
      - opentelemetry-proto==1.38.0
      - opentelemetry-sdk==1.38.0
      - opentelemetry-semantic-conventions==0.59b0
      - opentelemetry-util-http==0.59b0
      - orjson==3.11.4
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.3.3
      - posthog==7.0.1
      - propcache==0.4.1
      - protobuf==6.33.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.10.0
      - pydantic-core==2.27.0
      - pydantic-settings==2.12.0
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - pyreadline3==3.5.4
      - python-dotenv==1.0.1
      - python-multipart==0.0.12
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rich==14.2.0
      - rsa==4.9.1
      - shellingham==1.5.4
      - sniffio==1.3.1
      - sqlalchemy==2.0.35
      - starlette==0.38.6
      - sympy==1.14.0
      - tenacity==9.1.2
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - tqdm==4.67.1
      - typer==0.20.0
      - typer-slim==0.20.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.3.0
      - uvicorn==0.32.0
      - watchfiles==1.1.1
      - websocket-client==1.9.0
      - websockets==15.0.1
      - wrapt==1.17.3
      - yarl==1.22.0
prefix: C:\Users\SBA\miniconda3\envs\seoul
